# Generated by Django 6.0.1 on 2026-01-12 11:14

import devices.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('oxygen_concentrator', 'Oxygen Concentrator'), ('ventilator', 'Ventilator'), ('monitor', 'Patient Monitor'), ('wheelchair', 'Wheelchair'), ('other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('needs_repair', 'Needs Repair')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('picked_up', 'Picked Up'), ('under_inspection', 'Under Inspection'), ('under_repair', 'Under Repair'), ('certified', 'Certified'), ('listed', 'Listed'), ('allocated', 'Allocated')], default='submitted', max_length=20)),
                ('admin_approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_hold', 'On Hold')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes for approval/rejection')),
                ('listing_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=devices.models.device_image_upload)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='devices.device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('submitted', 'Submitted'), ('picked_up', 'Picked Up'), ('under_inspection', 'Under Inspection'), ('under_repair', 'Under Repair'), ('certified', 'Certified'), ('listed', 'Listed'), ('allocated', 'Allocated')], max_length=20)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('picked_up', 'Picked Up'), ('under_inspection', 'Under Inspection'), ('under_repair', 'Under Repair'), ('certified', 'Certified'), ('listed', 'Listed'), ('allocated', 'Allocated')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='devices.device')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
