# Generated by Django 6.0.1 on 2026-01-12 11:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('country', models.CharField(default='India', max_length=64)),
                ('state', models.CharField(blank=True, max_length=64)),
                ('district', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
                'ordering': ['country', 'state', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemBottleneckSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('pending_approvals', models.PositiveIntegerField(default=0)),
                ('pending_repairs', models.PositiveIntegerField(default=0)),
                ('pending_pickups', models.PositiveIntegerField(default=0)),
                ('in_transit_deliveries', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Bottleneck Snapshot',
                'verbose_name_plural': 'System Bottleneck Snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiaries', models.PositiveIntegerField(default=0)),
                ('estimated_co2_saved_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='devices.device')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_impacts', to='analytics.region')),
            ],
            options={
                'verbose_name': 'Device Impact',
                'verbose_name_plural': 'Device Impacts',
            },
        ),
    ]
